# Generated by Django 3.0.2 on 2020-02-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
