# Generated by Django 2.2.7 on 2020-02-02 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200201_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=1, help_text='№ пут. листа', max_length=20)),
                ('date_in', models.DateField(default=datetime.date.today, max_length=20, null=True)),
                ('date_out', models.DateField(default=datetime.date.today, max_length=20, null=True)),
                ('company', models.CharField(default='New company', help_text='Организация', max_length=50)),
                ('cab_number', models.CharField(default='Cab. number', help_text='№ каб. врача', max_length=5)),
                ('full_name', models.CharField(default='Full name', help_text='ФИО клиента', max_length=100)),
                ('birth_year', models.CharField(default='Birth YEAR', help_text='Год рождения', max_length=12)),
                ('passport', models.CharField(default='Passport', help_text='Паспорт / пенсионное', max_length=50)),
                ('address', models.CharField(default='Address', help_text='Домашний адресс', max_length=200)),
                ('early_departure', models.DateField(default=datetime.date.today, max_length=20, null=True)),
                ('black_list', models.NullBooleanField(default=True)),
                ('note', models.CharField(default='Notes', help_text='Комментарий', max_length=500)),
            ],
        ),
    ]
