# Generated by Django 2.2.7 on 2020-02-03 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='early_departure',
            field=models.DateField(blank=True, default=datetime.date.today, max_length=20, null=True),
        ),
    ]
