# Generated by Django 2.2.7 on 2020-02-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200203_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.CharField(blank=True, default='group', help_text='group', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='male',
            field=models.CharField(blank=True, default='male', help_text='male', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pay',
            field=models.CharField(blank=True, default='pay', help_text='pay', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='phone', help_text='phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='room',
            field=models.CharField(blank=True, default='room', help_text='Room', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, default='Notes', help_text='Комментарий', max_length=500, null=True),
        ),
    ]
