# Generated by Django 2.2.7 on 2020-02-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200207_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='black_list',
            field=models.CharField(choices=[('Неизвестно', 'Неизвестно'), ('Белый', 'Белый'), ('Черный', 'Черный')], default='black_list', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.CharField(choices=[('Пенсионер', 'Пенсионер'), ('Инвалид', 'Инвалид'), ('Глухонемой', 'Глухонемой'), ('Общество слепых', 'Общество слепых')], default='group', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='male',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='pay',
            field=models.CharField(choices=[('Бюджет', 'Бюджет'), ('Наличка', 'Наличка'), ('Перечисление', 'Перечисление')], default='pay', max_length=20),
        ),
    ]
